name: Merge queue test

on:
  merge_queue:

jobs:
  test-mq:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Print rustup components
        run: |
          rustup toolchain list -v
          rustc --version

      - name: Sleep
        run:
          sleep 120
          exit 0
