name: Test

on:
  pull_request:

jobs:
  sleep-30:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
  dynamic:
    runs-on: ubuntu-latest
    steps:
      - run: |
          commit_msg=${{ github.event.head_commit.message }}
          if [[ $commit_msg == *"fail"* ]]; then
            exit 1
          fi
