name: Test

on:
  pull_request:

jobs:
  test:
    name: Test before conclusion
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: |
          sleep 60
          exit 1
  conclusion:
    needs: [ test ]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Conclusion
        run:
          exit 0
