name: Workflow 2

on:
  push:
    branches:
      - automation/bors/try

jobs:
  test:
    name: Workflow 2 job 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run command
        run: |
          sleep 5
          exit 0
