name: Test

on:
  push:
    branches:
      - automation/bors/try

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run command
        run:
          exit 0
