name: Test

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  conclusion:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 30
      - name: Conclusion
        run:
          exit 0
