name: Test 2

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  conclusion:
    # Foo
    runs-on: ubuntu-latest
    steps:
      - name: Conclusion
        run:
          exit 0
