name: Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run command
        run:
          exit 0

      - uses: ./.github/workflows/composite1
        env:
          FOO: BAR
