name: Workflow 1

on:
  push:
    branches:
      - automation/bors/try

jobs:
  test:
    name: Workflow 1 job 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run command
        run:
          exit 0
  test2:
    name: Workflow 1 job 2
    runs-on: ubuntu-latest
    steps:
      - name: Run command
        run:
          exit 1
